### ISSUE TITLE
Implement new tracking events

### ISSUE THREAD

**Issue by tomalec** [woocommerce/pinterest-for-woocommerce#232]
There is a list of WooCommerce Tracking events we would like to trigger in the plugin, to be able to analyze how the plugin is being used.
A comprehensive list of all events is available at https://docs.google.com/spreadsheets/d/1u25mOcsODgcdPMy_rIagUAWHCfzsvJI1e8UPrJvYtVE/edit#gid=903716843

### Describe the solution you'd like 

- [x] Ensure all the dependencies and libraries needed are in place and in up-to-date versions.
- [ ] Implement individual events (each should be prefixed with `wcadmin_pfw_`): 
   - [x] `page_view`	n/a		When viewing wc react powered page. Default wc-admin event.
   - [x] ~`disconnected_account_link_click`~ `account_disconnect_button_click { context: 'settings' }` (see [below](https://github.com/woocommerce/pinterest-for-woocommerce/issues/232#issuecomment-1002184777))			When acocunt is disconnected rom the setting page https://d.pr/i/s7Oh7T  https://github.com/woocommerce/pinterest-for-woocommerce/pull/313
   - [x] `documentation_link_click`			When clicking documentation link e.g. https://d.pr/i/nSI71V, https://d.pr/i/COCw3G  and https://d.pr/i/plH2LQ 	https://github.com/woocommerce/pinterest-for-woocommerce/pull/261		
   - [x] `get_started_faq`			Clicking on getting started page faq item to collapse or expand it https://d.pr/i/CP6WPF - https://github.com/woocommerce/pinterest-for-woocommerce/pull/237
   - [x] `get_started_notice_link_click`			Clicking on a text link within the notice on the Get Started page https://d.pr/i/NWRC2W  https://github.com/woocommerce/pinterest-for-woocommerce/pull/299
   - [ ] `help_click`		**Not needed yet**	Triggered when the "Help" button is clicked.
   - [x] `account_connect_button_click`			https://d.pr/i/E3rtBZ - https://github.com/woocommerce/pinterest-for-woocommerce/pull/239
   - [x] `account_create_button_click`			https://d.pr/i/E3rtBZ  - https://github.com/woocommerce/pinterest-for-woocommerce/pull/239
   - [x] `modal_closed`			Triggered when a modal is closed https://github.com/woocommerce/pinterest-for-woocommerce/pull/290
   - ~[ ] `modal_content_link_click`			Triggered when clicking on a text link within the modal content~ currently there is no link in the modal.
   - [x] `modal_open`			Triggered when a modal is opened/displayed https://d.pr/i/AUJddy https://github.com/woocommerce/pinterest-for-woocommerce/pull/290
   - [x] `save_changes_button_click`			Triggered when save changes button is clicked https://d.pr/i/4CiZgY https://github.com/woocommerce/pinterest-for-woocommerce/pull/295
   - [x] `setup`			Triggered on events during setup e.g. get start button click https://d.pr/i/HGg9Mj  or header buttons clicked https://d.pr/i/7BlNRu or continue button e.g. https://d.pr/i/wADg9P https://d.pr/i/YoyLP2  https://github.com/woocommerce/pinterest-for-woocommerce/pull/308
   - [x] `domain_verify_failure`			When a site verification fails https://github.com/woocommerce/pinterest-for-woocommerce/pull/300
   - [x] `domain_verify_success`			When a site is successfully verified https://d.pr/i/4NLnzy  https://github.com/woocommerce/pinterest-for-woocommerce/pull/314
   - [ ] `able_header_toggle`		**not needed yet**	When table columns/headers are toggle by a user e.g. Product Feed table
   - [ ] `table_sort`		**not needed yet**	When table column is sorted by a user
   - [ ] `table_go_to_page`		**not needed yet**	When table pagination is changed by "Go to page" input
   - [ ] `table_page_click`		**not needed yet**	When table pagination is clicked
   - [ ] `tooltip_viewed`		**not needed yet**	When a tooltip (helptip) is viewed/clicked
- [x] (Nice to have) Implement some automation for translating code docs for events to aggregated docs. https://github.com/woocommerce/google-listings-and-ads/issues/117 - https://github.com/woocommerce/pinterest-for-woocommerce/pull/238

Additional ones, implemented by the way:
- Account related https://github.com/woocommerce/pinterest-for-woocommerce/pull/239
	 - `account_convert_button_click`
	 - `account_disconnect_button_click`
	 - `account_create_button_click`
	 - `business_account_connect_button_click`
- [x] `wcadmin_pfw_ads_manager_link_click` When _"Pinterest ads manager"_ link is clicked [more...](https://github.com/woocommerce/pinterest-for-woocommerce/pull/296#pullrequestreview-842872047) https://github.com/woocommerce/pinterest-for-woocommerce/pull/316

### Feature branch

The feature will be tracked at https://github.com/woocommerce/pinterest-for-woocommerce/tree/feature/232-tracking

### Additional context 

- Existing issue related to Pinterest JS tracking https://github.com/woocommerce/pinterest-for-woocommerce/issues/28

//cc @jconroy

**Comment by findingsimple** [comment]
Thanks @tomalec 

As you are working through, if you spot anything else / interactions that would be useful to track let me know

**Comment by puntope** [comment]
@jconroy @tomalec 

I'm checking `disconnected_account_link_click` task but somehow I cannot find it in Settings Tab.

**Comment by ianlin** [comment]
Brought the discussion here from https://github.com/woocommerce/pinterest-for-woocommerce/pull/295#discussion_r769543773 for event `save_changes_button_click`: triggered when save changes button is clicked.

Basically the questions is: **how do we name the event contexts, hard coded or extracted from the path?**

Would also like to know if there's any event naming convention that we can follow? Including event names, event contexts, and event actions.

**Comment by tomalec** [comment]
While implementing the `setup` event, I decided to change the values, description and meaning behind properties.

Originally it was:
> target: button ID
> trigger: action (e.g. click)

For all the buttons, the action would be most probably "click". Technically it could be "tap", "keypress" if we would like to record differentiate between different pointing/accessibility devices - but I suspect that may not be what we would like to analyze.

I guess we'd rather track: "How a user proceeds through the setup, and by activating what UI elements?" So, I propose to use the following properties:
```
 * @property {string} target Setup phase that the user navigates to, like `'onboarding', 'step-claim-website'`.
 * @property {string} trigger UI element that triggered the action, e.g. `wizard-stepper` or `get-started` button.
 ```
 
 @jconroy please tell me WDYT?

**Comment by tomalec** [comment]
> `disconnected_account_link_click` When acocunt is disconnected rom the setting page d.pr/i/s7Oh7T

For the setup process, I added `account_disconnect_button_click` that is consistent in naming with other account-related events (`account_*_button_click`).
As this is the same UI component, but used in two different contexts, I propose to follow the same path we took for other events and use that same name in settings and onboarding wizard but add the `context` property.

**Comment by tomalec** [comment]
@jconroy  I'd appreciate your approval on the following changes to the original spreadsheet:
- [x] `disconnected_account_link_click` was renamed to `account_disconnect_button_click` with additional `context` property and is fired on both wizard and settings views. [more…](https://github.com/woocommerce/pinterest-for-woocommerce/issues/232#issuecomment-1002184777)
- [x] `setup` events' props have different names meaning & desc [more…](https://github.com/woocommerce/pinterest-for-woocommerce/issues/232#issuecomment-998968676)
   * `target` Setup phase that the user navigates to, like `'onboarding', 'step-claim-website'`.
   * `trigger` UI element that triggered the action, e.g. `wizard-stepper` or `get-started`
- [x] added more events [more…](https://github.com/woocommerce/pinterest-for-woocommerce/pull/239)
	  - `account_convert_button_click`
	  - `account_disconnect_button_click`
	  - `account_create_button_click`
	  - `business_account_connect_button_click`
- [x]  `wcadmin_pfw_modal_open` has new `name` prop and different meaning of `context` [more…](https://github.com/woocommerce/pinterest-for-woocommerce/pull/290#issuecomment-996734416):
   - `name` What modal is it? // To be future prepared for other kinds of modals
   - `context` Indicate in what context it was opened. 
- [x] `wcadmin_pfw_ads_manager_link_click` I'll add another event [more...](https://github.com/woocommerce/pinterest-for-woocommerce/pull/296#pullrequestreview-842872047) https://github.com/woocommerce/pinterest-for-woocommerce/pull/316
 
 All the events are documented at https://github.com/woocommerce/pinterest-for-woocommerce/blob/bac507719c8f5ea7f384fc9f125a10a5857e3714/TRACKING.md

**Comment by findingsimple** [comment]
Thanks @tomalec I think that all looks a-ok to me - thank you! If we can update the spreadsheet accordingly I'll be able to transpose and update other locations

**Comment by tomalec** [comment]
Tracks are implemented and merged in the `develop` branch now. The only thing left here is to update the spreadsheet with the state documented in https://github.com/woocommerce/pinterest-for-woocommerce/blob/develop/TRACKING.md. I'll do that once, I get the editing access.

**Comment by tomalec** [comment]
Spread sheet updated, closing as done.
